// src/data/users.js
export const users = [
  {
    id: 1,
    name: "سارة الأحمد",
    role: "مهندسة واجهات أمامية",
    email: "sara.ahmad@example.com",
    phone: "+963 999 111 222",
    avatar: "https://i.pravatar.cc/150?img=47",
    location: "دمشق، سوريا",
    status: "online",
    joinedDate: "2023-03-15",
    bio: "متخصصة في React و Tailwind، أعمل على تصميم أنظمة تصميم قابلة لإعادة الاستخدام.",
    skills: ["React", "TypeScript", "Tailwind", "Figma"],
    stats: { projects: 24, followers: 340, following: 120 },
    isVerified: true,
    rating: 4.8,
  },
  {
    id: 2,
    name: "محمد الخطيب",
    role: "مطور باك-إند",
    email: "m.khatib@example.com",
    phone: "+963 999 333 444",
    avatar: "https://i.pravatar.cc/150?img=12",
    location: "حلب، سوريا",
    status: "busy",
    joinedDate: "2022-11-01",
    bio: "أبني واجهات برمجية بـ Node.js و NestJS، مهتم بقواعد البيانات وأداء الخوادم.",
    skills: ["Node.js", "NestJS", "PostgreSQL", "Docker"],
    stats: { projects: 41, followers: 210, following: 88 },
    isVerified: true,
    rating: 4.6,
  },
  {
    id: 3,
    name: "ليان حسن",
    role: "مصممة تجربة مستخدم",
    email: "layan.hassan@example.com",
    phone: "+963 999 555 666",
    avatar: "https://i.pravatar.cc/150?img=32",
    location: "اللاذقية، سوريا",
    status: "offline",
    joinedDate: "2024-01-20",
    bio: "أصمم تجارب رقمية تركز على المستخدم، مع خلفية في علم النفس المعرفي.",
    skills: ["UX Research", "Figma", "Prototyping", "Design Systems"],
    stats: { projects: 17, followers: 520, following: 210 },
    isVerified: false,
    rating: 4.9,
  },
  {
    id: 4,
    name: "عمر النجار",
    role: "مهندس DevOps",
    email: "omar.najjar@example.com",
    phone: "+963 999 777 888",
    avatar: "https://i.pravatar.cc/150?img=15",
    location: "حمص، سوريا",
    status: "online",
    joinedDate: "2021-06-10",
    bio: "أتولى أتمتة النشر والمراقبة، وأعمل على تحسين وقت البناء في مشاريع كبيرة.",
    skills: ["Kubernetes", "CI/CD", "Terraform", "AWS"],
    stats: { projects: 33, followers: 180, following: 95 },
    isVerified: true,
    rating: 4.5,
  },
  {
    id: 5,
    name: "ريم العلي",
    role: "مطورة موبايل",
    email: "reem.ali@example.com",
    phone: "+963 999 999 000",
    avatar: "https://i.pravatar.cc/150?img=44",
    location: "حماة، سوريا",
    status: "busy",
    joinedDate: "2023-08-05",
    bio: "أطوّر تطبيقات React Native و Flutter، وأحب العمل على التفاصيل الدقيقة للواجهة.",
    skills: ["React Native", "Flutter", "Firebase", "GraphQL"],
    stats: { projects: 22, followers: 410, following: 150 },
    isVerified: true,
    rating: 4.7,
  },
  {
    id: 6,
    name: "خالد مرعي",
    role: "محلل بيانات",
    email: "khaled.marei@example.com",
    phone: "+963 999 121 212",
    avatar: "https://i.pravatar.cc/150?img=18",
    location: "دير الزور، سوريا",
    status: "offline",
    joinedDate: "2022-02-14",
    bio: "أحوّل البيانات إلى قرارات، أعمل على لوحات معلومات تفاعلية وتقارير آلية.",
    skills: ["Python", "Pandas", "SQL", "Power BI"],
    stats: { projects: 29, followers: 260, following: 130 },
    isVerified: false,
    rating: 4.4,
  },
  {
    id: 7,
    name: "نور الدين",
    role: "كاتب محتوى تقني",
    email: "nour.din@example.com",
    phone: "+963 999 343 434",
    avatar: "https://i.pravatar.cc/150?img=68",
    location: "طرطوس، سوريا",
    status: "online",
    joinedDate: "2024-04-02",
    bio: "أكتب مقالات تقنية بالعربية، وأبسّط المفاهيم المعقدة للمبتدئين.",
    skills: ["Technical Writing", "SEO", "Markdown", "Docs"],
    stats: { projects: 12, followers: 890, following: 75 },
    isVerified: true,
    rating: 4.9,
  },
  {
    id: 8,
    name: "هبة قاسم",
    role: "مديرة منتج",
    email: "heba.qasem@example.com",
    phone: "+963 999 565 656",
    avatar: "https://i.pravatar.cc/150?img=49",
    location: "دمشق، سوريا",
    status: "busy",
    joinedDate: "2020-09-30",
    bio: "أربط بين رؤية العمل والتنفيذ التقني، وأقود فرقًا متعددة التخصصات.",
    skills: ["Roadmapping", "Agile", "Analytics", "Stakeholder Mgmt"],
    stats: { projects: 38, followers: 610, following: 240 },
    isVerified: true,
    rating: 4.8,
  },
];
